export const events = [
  {
    title: "Next.js Conf 2026",
    image: "/images/event1.png",
    slug: "nextjs-conf-2026",
    location: "San Francisco, CA",
    date: "Jun 12, 2026",
    time: "9:00 AM PST",
  },
  {
    title: "React Summit",
    image: "/images/event2.png",
    slug: "react-summit",
    location: "Amsterdam, Netherlands",
    date: "Jun 17, 2026",
    time: "10:00 AM CET",
  },
  {
    title: "HackMIT 2026",
    image: "/images/event3.png",
    slug: "hackmit-2026",
    location: "Cambridge, MA",
    date: "Jul 5–6, 2026",
    time: "12:00 PM EST",
  },
  {
    title: "Google I/O Extended",
    image: "/images/event4.png",
    slug: "google-io-extended",
    location: "Mountain View, CA",
    date: "Jul 20, 2026",
    time: "10:00 AM PST",
  },
  {
    title: "JSNation Conference",
    image: "/images/event5.png",
    slug: "jsnation-conference",
    location: "Berlin, Germany",
    date: "Aug 3, 2026",
    time: "9:30 AM CET",
  },
  {
    title: "DevFest Global",
    image: "/images/event6.png",
    slug: "devfest-global",
    location: "Lagos, Nigeria",
    date: "Sep 14, 2026",
    time: "11:00 AM WAT",
  },
];
